/* Generated by `python -m engram.export_types` — do not edit. */
export interface GraphEdge {
  id: string | null;
  source: string;
  target: string;
  type: string;
  weight: number;
}

export interface GraphEvidence {
  kind: string;
  content: string | null;
  importance: number | null;
}

export interface GraphNode {
  id: string;
  label: string;
  type: string;
  summary: string | null;
  mastery: number | null;
  confidence: number | null;
  salience: number | null;
  importance: number | null;
  evidence: GraphEvidence[];
}

export interface MemGraphResponse {
  enabled: boolean;
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export interface MemAuditRow {
  id: string;
  op: string;
  rationale: string | null;
  model: string | null;
  tokens: number | null;
  cost: number | null;
  ts: string | null;
}

export interface MemAuditResponse {
  enabled: boolean;
  rows: MemAuditRow[];
}

export interface MemHealthResponse {
  enabled: boolean;
  healthy: boolean;
}

export interface MemStatusResponse {
  consolidating: boolean;
}

export interface RecallSubgraph {
  nodes: unknown[];
  edges: unknown[];
}

export interface RecallProbeResponse {
  enabled: boolean;
  text_block: string;
  subgraph: RecallSubgraph;
}

export interface AuditRow {
  id: string;
  op: string;
  rationale: string | null;
  model: string | null;
  tokens: number | null;
  cost: number | null;
  ts: string;
}
