"""Emit TypeScript interfaces from a fixed list of Pydantic models.

Usage: ``python -m engram.export_types [out.ts]``

Default output: ``packages/engram-types/index.d.ts`` (the ``@engram/types`` npm package).

Stdlib only. Supported JSON Schema subset: string/number/integer/boolean/null,
arrays, ``$ref``/``$defs``, unions via ``anyOf``. Anything else → ``unknown``.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from engram.app.schemas import AuditRow, GraphEdge, GraphNode
from engram.integrations.fastapi import (
    MemAuditResponse,
    MemAuditRow,
    MemGraphResponse,
    MemHealthResponse,
    MemStatusResponse,
    RecallProbeResponse,
)

MODELS: list[type[BaseModel]] = [
    MemGraphResponse,
    MemAuditRow,
    MemAuditResponse,
    MemHealthResponse,
    MemStatusResponse,
    RecallProbeResponse,
    GraphNode,
    GraphEdge,
    AuditRow,
]

_PRIM = {
    "string": "string",
    "number": "number",
    "integer": "number",
    "boolean": "boolean",
    "null": "null",
}


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _type_of(schema: dict[str, Any], defs: dict[str, Any]) -> str:
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    if "anyOf" in schema:
        return " | ".join(_type_of(s, defs) for s in schema["anyOf"])
    t = schema.get("type")
    if isinstance(t, list):  # rare multi-type
        return " | ".join(_PRIM.get(x, "unknown") for x in t)
    if t in _PRIM:
        return _PRIM[t]
    if t == "array":
        inner = _type_of(schema.get("items") or {}, defs)
        if " | " in inner:
            return f"({inner})[]"
        return f"{inner}[]"
    if t == "object" or "properties" in schema:
        # bare object (e.g. list[dict]) — not a named interface
        if "properties" not in schema:
            return "unknown"
        # inline object with properties (shouldn't appear for our models)
        return "unknown"
    return "unknown"


def _iface(name: str, schema: dict[str, Any], defs: dict[str, Any]) -> str:
    # ponytail: no `?` optionals — pydantic always serializes these response fields
    props = schema.get("properties") or {}
    lines = [f"export interface {name} {{"]
    for key, prop in props.items():
        lines.append(f"  {key}: {_type_of(prop, defs)};")
    lines.append("}")
    return "\n".join(lines)


def emit_ts(models: list[type[BaseModel]] | None = None) -> str:
    models = models or MODELS
    seen: dict[str, str] = {}
    order: list[str] = []
    def _record(iname: str, ischema: dict, defs: dict) -> None:
        iface = _iface(iname, ischema, defs)
        if iname in seen:
            # Two distinct models sharing a name would silently emit one shape
            # for both — a .ts that typechecks but mismatches the wire. Fail loud.
            if seen[iname] != iface:
                raise ValueError(
                    f"TS export name collision: {iname!r} has two different shapes; "
                    "rename one model or namespace the export.")
            return
        seen[iname] = iface
        order.append(iname)

    for model in models:
        schema = model.model_json_schema()
        defs = schema.get("$defs") or {}
        for dname, dschema in defs.items():
            _record(dname, dschema, defs)
        title = schema.get("title") or model.__name__
        _record(title, schema, defs)
    header = (
        "/* Generated by `python -m engram.export_types` — do not edit. */\n"
    )
    return header + "\n\n".join(seen[n] for n in order) + "\n"


# Canonical npm package path (repo-root relative). Override with CLI arg.
_DEFAULT_OUT = Path("packages/engram-types/index.d.ts")


def main(argv: list[str] | None = None) -> None:
    argv = argv if argv is not None else sys.argv[1:]
    out = Path(argv[0]) if argv else _DEFAULT_OUT
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(emit_ts(), encoding="utf-8")
    print(f"wrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
